runtime: custom
env: flex

# TODO(redbrogdon): remove this line when ready to merge.
service: flutter-web-unforked

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 50

automatic_scaling:
  # TODO(redbrogdon): set back to 6 before merging.
  min_num_instances: 1
  max_num_instances: 40
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  REDIS_SERVER_URI: 'redis://10.0.0.4:6379'

network:
  name: vpc-dart-services

skip_files:
- ^\.git/.*$

liveness_check:
  path: /_ah/health

readiness_check:
  path: /_ah/ready
